options:
  install_sources:
    type: string
    default: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    description: apt repository to fetch beats from
  install_keys:
    type: string
    default: D88E42B4
    description: repository key
  procs:
    type: string
    default: ".*"
    description: Process regex to pass to the monitor. To disable process filtering, set ^$
  period:
    type: int
    default: 10
    description: how often in seconds to read system-wide and per-process statistics
